from pathlib import Path
import json,re,hashlib,collections
ROOT=Path(__file__).resolve().parents[3]
OUT=ROOT/'site/assets/respiratory'
SRC=Path.home() / 'Documentos/Anatomia_Circulatorio_Respiratorio_2026-09-28'
VAULT=Path.home() / 'Documentos/My vault/Obsidian vault/Medicina Uem/Anatomia/Aulas Carmem - Circulatório e Respiratório'
zinv=json.loads((ROOT/'malhas/z_blend_inventory.json').read_text())['objects']
znames={o['name']:o for o in zinv if o['type'] in ['MESH','CURVE'] and (o.get('polygons',0)>0 or o.get('surface_curve',False))}
rows=[]
def add(group,label,page,names='',kind='estrutura',scope='principal'):
 cand=[]
 for name in names.split('|'):
  if not name:continue
  if name.endswith('.*'):cand.extend(n for n in znames if n in [name[:-2]+'.l',name[:-2]+'.r'])
  elif name in znames:cand.append(name)
 rows.append({'id':f'R{len(rows)+1:03d}','estrutura':label,'grupo':group,'fonte':'resp_slides' if page else 'roteiro_complementar','pagina':page,'escopo':scope,'tipo':kind,'status':'geometria_disponivel' if cand and kind=='estrutura' else ('parcial_ou_a_conferir' if cand else 'nao_localizado'),'z_evidencia':cand,'validacao_visual':'pendente_individual','origem_escopo':'Derivado dos slides de Carmem; não é roteiro oficial de prova confirmado.' if page else 'Lista complementar de Cláudia Pinheiro; não é roteiro oficial de Carmem.','coverageClaim':'Disponibilidade nominal não certifica forma, posição ou completude.'})
# Order is the stable ID contract; append new targets, never insert above existing IDs.
g='Nariz e cavidade nasal'
for label,page,names,kind in [
('Ápice do nariz',11,'Nasal region.*','regiao'),('Raiz do nariz',11,'Nasal region.*','regiao'),('Dorso do nariz',11,'Nasal region.*','regiao'),('Narinas',11,'Nasal region.*','abertura'),('Asas do nariz',11,'Nasal region.*','regiao'),('Ossos nasais',11,'Nasal bone.*','estrutura'),('Maxilas',16,'Maxilla.*','estrutura'),('Cartilagem do septo nasal',17,'Nasal septal cartilage','estrutura'),('Cartilagens nasais laterais',11,'Lateral process of nasal septal cartilage.*','estrutura'),('Cartilagens alares maiores',11,'Major alar cartilage.*','estrutura'),('Cartilagens alares menores',11,'Lesser alar cartilage.*','estrutura'),('Vestíbulo nasal',14,'Mucosa of nasal cavity','regiao'),('Vibrissas',14,'','microestrutura'),('Lâmina perpendicular do etmoide',17,'Ethmoid bone','regiao'),('Vômer',17,'Vomer','estrutura'),('Lâmina cribriforme do etmoide',18,'Ethmoid bone','regiao'),('Crista etmoidal (crista galli)',18,'Ethmoid bone','regiao'),('Massas laterais do etmoide',18,'Ethmoid bone','regiao'),('Conchas nasais superiores',18,'Ethmoid bone|Mucosa of nasal cavity','regiao'),('Conchas nasais médias',18,'Ethmoid bone|Mucosa of nasal cavity','regiao'),('Conchas nasais inferiores',19,'Inferior nasal concha bone.*','estrutura'),('Meatos nasais superiores',36,'Mucosa of nasal cavity','espaco'),('Meatos nasais médios',36,'Mucosa of nasal cavity','espaco'),('Meatos nasais inferiores',36,'Mucosa of nasal cavity','espaco'),('Cóanos',19,'Mucosa of nasal cavity|Vomer|Palatine bone.*','abertura'),('Palato duro: processo palatino da maxila',19,'Maxilla.*','regiao'),('Palato duro: lâmina horizontal do palatino',19,'Palatine bone.*','regiao'),('Região respiratória da mucosa nasal',20,'Mucosa of nasal cavity','regiao'),('Região olfatória da mucosa nasal',20,'Mucosa of nasal cavity','regiao'),('Músculo prócero',12,'Procerus muscle','estrutura'),('Músculo nasal',12,'Nasalis muscle.*','estrutura'),('Levantador do lábio superior e da asa do nariz',12,'Levator labii superioris alaeque nasi muscle.*','estrutura'),('Abaixador do septo nasal',12,'Depressor septi nasi muscle','estrutura')]:add(g,label,page,names,kind)
g='Seios paranasais'
for label,page,names in [('Seios frontais',34,'Sinus of frontal bone'),('Seios maxilares',34,'Maxillary sinus.*'),('Seios esfenoidais',34,'Sinus of sphenoid bone'),('Células etmoidais anteriores',36,'Anterior cells of ethmoid bone.*'),('Células etmoidais médias',36,'Middle cells of ethmoid bone.*'),('Células etmoidais posteriores',36,'Posterior cells of ethmoid bone.*')]:add(g,label,page,names)
add(g,'Bolha etmoidal',36,'Ethmoid bone|Mucosa of nasal cavity','regiao');add(g,'Recesso esfenoetmoidal',36,'Mucosa of nasal cavity','espaco')
g='Faringe'
for label,page,names,kind in [('Nasofaringe',42,'Nasopharynx','estrutura'),('Orofaringe',42,'Oropharynx','estrutura'),('Laringofaringe',42,'Laryngopharynx','estrutura'),('Óstio faríngeo da tuba auditiva',44,'Nasopharynx','abertura'),('Toro tubário',44,'Nasopharynx','regiao'),('Prega salpingopalatina',44,'Nasopharynx','regiao'),('Prega salpingofaríngea',44,'Nasopharynx','regiao'),('Tonsila faríngea',44,'Pharyngeal tonsil','estrutura'),('Tonsilas tubárias',44,'Tubal tonsil.*','estrutura'),('Tonsilas palatinas',45,'Palatine tonsil.*','estrutura'),('Tonsila lingual',45,'Lingual tonsil','estrutura'),('Úvula palatina',44,'Uvula of palate','estrutura'),('Palato mole',42,'Soft palate','estrutura'),('Constritores superiores da faringe',47,'Superior pharyngeal constrictor.*','estrutura'),('Constritores médios da faringe',47,'Middle pharyngeal constrictor.*','estrutura'),('Constritores inferiores da faringe',48,'Inferior pharyngeal constrictor.*','estrutura'),('Músculos estilofaríngeos',48,'Stylopharyngeus muscle.*','estrutura'),('Músculos salpingofaríngeos',49,'Salpingopharyngeus muscle.*','estrutura'),('Músculos palatofaríngeos',49,'Palatopharyngeus muscle.*','estrutura')]:add(g,label,page,names,kind)
g='Laringe: cartilagens e membranas'
for label,page,names,kind in [('Cartilagem tireóidea',56,'Thyroid cartilage','estrutura'),('Lâminas da cartilagem tireóidea',56,'Thyroid cartilage','regiao'),('Proeminência laríngea',56,'Thyroid cartilage','regiao'),('Linha oblíqua da tireóidea',56,'Thyroid cartilage','regiao'),('Incisura tireóidea superior',56,'Thyroid cartilage','regiao'),('Incisura tireóidea inferior',56,'Thyroid cartilage','regiao'),('Cornos superiores da tireóidea',56,'Thyroid cartilage','regiao'),('Cornos inferiores da tireóidea',56,'Thyroid cartilage','regiao'),('Membrana tireo-hióidea',56,'Thyrohyoid membrane','estrutura'),('Ligamento tireo-hióideo mediano',56,'Median thyrohyoid ligament','estrutura'),('Ligamentos tireo-hióideos laterais',56,'Lateral thyrohyoid ligament.*','estrutura'),('Cartilagem cricóidea',57,'Cricoid cartilage','estrutura'),('Arco da cartilagem cricóidea',57,'Cricoid cartilage','regiao'),('Lâmina da cartilagem cricóidea',58,'Cricoid cartilage','regiao'),('Articulações cricotireóideas',57,'Thyroid cartilage|Cricoid cartilage','articulacao'),('Articulações cricoaritenóideas',58,'Cricoid cartilage|Arytenoid cartilage.*','articulacao'),('Ligamento cricotireóideo mediano',57,'Median cricothyroid ligament','estrutura'),('Ligamento cricotraqueal',57,'Cricotracheal ligament','estrutura'),('Cartilagem epiglótica / epiglote',61,'Epiglottis','estrutura'),('Pecíolo da epiglote',61,'Epiglottis','regiao'),('Ligamento tireoepiglótico',62,'Thyroepiglottic ligament','estrutura'),('Ligamento hioepiglótico',62,'Hyoepiglottic ligament','estrutura'),('Pregas glossoepiglóticas mediana e laterais',63,'Epiglottis','regiao'),('Valéculas epiglóticas',63,'Epiglottis','espaco'),('Cartilagens aritenóideas',64,'Arytenoid cartilage.*','estrutura'),('Processos vocais das aritenóideas',64,'Arytenoid cartilage.*','regiao'),('Processos musculares das aritenóideas',64,'Arytenoid cartilage.*','regiao'),('Cartilagens corniculadas',64,'Corniculate cartilage.*','estrutura'),('Cartilagens cuneiformes',55,'Cuneiform cartilage.*','estrutura')]:add(g,label,page,names,kind)
g='Laringe: músculos e cavidade'
for label,page,names,kind in [('Músculos cricotireóideos: partes reta e oblíqua',66,'Straight part of cricothyroid muscle.*|Oblique part of cricothyroid muscle.*','estrutura'),('Músculos aritenóideos oblíquos',66,'Oblique arytenoid muscle.*','estrutura'),('Músculo aritenóideo transverso',66,'Transverse arytenoid muscle','estrutura'),('Músculos cricoaritenóideos laterais',66,'Lateral crico-arytenoid muscle.*','estrutura'),('Músculos tireoaritenóideos',66,'External part of thyro-arytenoid muscle.*','estrutura'),('Músculos tireoepiglóticos',66,'Thyro-epiglottic part of thyro-arytenoid muscle.*','estrutura'),('Músculos vocais',70,'Vocalis muscle.*','estrutura'),('Músculos cricoaritenóideos posteriores',66,'Posterior crico-arytenoid muscle.*','estrutura'),('Pregas vestibulares',72,'','regiao'),('Pregas vocais',72,'Vocal ligament.*','regiao'),('Vestíbulo da laringe',72,'','espaco'),('Ventrículos da laringe',72,'','espaco'),('Glote e rima da glote',72,'','espaco'),('Cavidade infraglótica',72,'','espaco')]:add(g,label,page,names,kind)
g='Traqueia'
for label,page,names,kind in [('Traqueia: parte cervical',84,'Trachea','regiao'),('Traqueia: parte torácica',84,'Trachea','regiao'),('Cartilagens traqueais',85,'Trachea','regiao'),('Ligamentos anulares da traqueia',85,'Trachea','regiao'),('Músculo traqueal',85,'Trachealis muscle','estrutura'),('Parede membranácea da traqueia',85,'Trachea','regiao'),('Carina da traqueia',85,'Trachea','regiao')]:add(g,label,page,names,kind)
g='Árvore brônquica'
for label,page,name in [('Brônquio principal direito',89,'Right main bronchus'),('Brônquio principal esquerdo',89,'Left main bronchus'),('Brônquio lobar superior direito',92,'Right superior lobar bronchus'),('Brônquio lobar médio direito',92,'Middle lobar bronchus.r'),('Brônquio lobar inferior direito',92,'Right inferior lobar bronchus'),('Brônquio lobar superior esquerdo',93,'Left superior lobar bronchus'),('Brônquio lobar inferior esquerdo',93,'Left inferior lobar bronchus'),('Brônquio intermédio direito',91,'Intermediate bronchus.r')]:add(g,label,page,name)
for label,name in [('apical','Apical segmental bronchus of right lung (BI)'),('posterior','Posterior segmental bronchus of right lung (BII)'),('anterior','Anterior segmental bronchus of right lung (BIII)'),('lateral do lobo médio','Lateral segmental bronchus of right lung (BIV)'),('medial do lobo médio','Medial segmental bronchus of right lung (BV)'),('superior do lobo inferior','Superior segmental bronchus of right lung (BVI)'),('basilar medial','Medial basal segmental bronchus of right lung (BVII)'),('basilar anterior','Anterior basal segmental bronchus of right lung (BVIII)'),('basilar lateral','Lateral basal segmental bronchus of right lung (BIX)'),('basilar posterior','Posterior basal segmental bronchus of right lung (BX)')]:add(g,'Brônquio segmentar direito: '+label,92,name)
for label,name in [('apicoposterior','Apicoposterior segmental bronchus of left lung (BI+BII)'),('anterior','Anterior segmental bronchus of left lung (BIII)'),('lingular superior','Superior lingular segmental bronchus of left lung (BIV)'),('lingular inferior','Inferior lingular segmental bronchus of left lung (BV)'),('superior do lobo inferior','Superior segmental bronchus of left lung (BVI)'),('basilar medial','Medial basal segmental bronchus of left lung (BVII)'),('basilar anterior','Anterior basal segmental bronchus of left lung (BVIII)'),('basilar lateral','Lateral basal segmental bronchus of left lung (BIX)'),('basilar posterior','Posterior basal segmental bronchus of left lung (BX)')]:add(g,'Brônquio segmentar esquerdo: '+label,93,name)
g='Pulmões'
lungs='Superior lobe of right lung|Middle lobe of right lung|Inferior lobe of right lung|Superior lobe of left lung|Inferior lobe of left lung'
for label,page,names,kind in [('Lobo superior direito',104,'Superior lobe of right lung','estrutura'),('Lobo médio direito',104,'Middle lobe of right lung','estrutura'),('Lobo inferior direito',104,'Inferior lobe of right lung','estrutura'),('Lobo superior esquerdo',104,'Superior lobe of left lung','estrutura'),('Lobo inferior esquerdo',104,'Inferior lobe of left lung','estrutura'),('Ápices pulmonares',101,'Superior lobe of right lung|Superior lobe of left lung','regiao'),('Bases pulmonares',101,'Inferior lobe of right lung|Inferior lobe of left lung','regiao'),('Faces costais',103,lungs,'regiao'),('Faces diafragmáticas',103,'Inferior lobe of right lung|Inferior lobe of left lung','regiao'),('Faces mediastinais',105,lungs,'regiao'),('Fissura horizontal direita',104,'Superior lobe of right lung|Middle lobe of right lung','espaco'),('Fissura oblíqua direita',104,'Superior lobe of right lung|Middle lobe of right lung|Inferior lobe of right lung','espaco'),('Fissura oblíqua esquerda',104,'Superior lobe of left lung|Inferior lobe of left lung','espaco'),('Hilos pulmonares',105,lungs,'regiao'),('Raízes / pedículos pulmonares',106,'Right main bronchus|Left main bronchus','conjunto'),('Língula do pulmão esquerdo',109,'Superior lobe of left lung','regiao'),('Incisura cardíaca esquerda',109,'Superior lobe of left lung','regiao'),('Impressão cardíaca esquerda',109,'Superior lobe of left lung|Inferior lobe of left lung','regiao'),('Sulcos pulmonares direitos para cavas, ázigos e esôfago',108,'Superior lobe of right lung|Inferior lobe of right lung','regiao'),('Sulcos esquerdos para arco aórtico, subclávia e esôfago',109,'Superior lobe of left lung|Inferior lobe of left lung','regiao')]:add(g,label,page,names,kind)
# Borders explicitly in complementary list; broad grouping does not imply separate official targets.
for label in ['Margens pulmonares anteriores','Margens pulmonares posteriores','Margens pulmonares inferiores']:add(g,label,None,lungs,'regiao','complementar')
g='Pleuras'
for label,page,names,kind in [('Pleura visceral',112,'Pleura','camada'),('Pleura parietal: parte costal',113,'Pleura','camada'),('Pleura parietal: parte diafragmática',114,'Pleura','camada'),('Pleura parietal: parte mediastinal',115,'Pleura','camada'),('Pleura cervical / cúpula pleural',116,'Pleura','camada'),('Cavidade pleural',110,'Pleura','espaco'),('Fáscia endotorácica',113,'Endothoracic fascia','estrutura'),('Fáscia frenicopleural',115,'','camada'),('Membrana suprapleural (Sibson)',116,'Suprapleural membrane.*','estrutura'),('Ligamento pulmonar',117,'','estrutura'),('Recessos costodiafragmáticos',118,'Pleura','espaco'),('Recessos costomediastinais',118,'Pleura','espaco')]:add(g,label,page,names,kind)
g='Vasos, nervos e linfáticos'
for label,page,names in [('Artéria pulmonar direita',126,'Right pulmonary artery'),('Artéria pulmonar esquerda',126,'Left pulmonary artery'),('Veias pulmonares direitas',126,'Right superior pulmonary vein|Right inferior pulmonary vein'),('Veias pulmonares esquerdas',126,'Left superior pulmonary vein|Left inferior pulmonary vein'),('Artérias brônquicas',123,''),('Veias brônquicas',124,''),('Plexo pulmonar anterior',128,''),('Plexo pulmonar posterior',128,''),('Nervos vagos',127,'Vagus nerve (X).*'),('Nervos frênicos',127,''),('Nervos intercostais',127,''),('Troncos simpáticos',127,'Sympathetic trunk.*'),('Linfonodos broncopulmonares (hilares)',129,'Bronchopulmonary nodes.*'),('Linfonodos traqueobronquiais inferiores',129,'Inferior tracheobronchial nodes'),('Linfonodos traqueobronquiais superiores',129,'Superior tracheobronchial nodes'),('Linfonodos paratraqueais',87,'Paratracheal cervical nodes|Paratracheal thoracic nodes')]:add(g,label,page,names)
for label,page in [('Plexo linfático superficial / subpleural',129),('Plexo linfático profundo',129),('Troncos broncomediastinais',129)]:add(g,label,page,'','microestrutura')
g='Zona respiratória e mecânica'
for label,page,names,kind in [('Bronquíolos terminais',8,'','microestrutura'),('Bronquíolos respiratórios',8,'','microestrutura'),('Ductos alveolares',8,'','microestrutura'),('Sacos alveolares',8,'','microestrutura'),('Alvéolos',8,'','microestrutura'),('Pneumócitos tipo I',131,'','microestrutura'),('Pneumócitos tipo II',131,'','microestrutura'),('Diafragma',138,'Diaphragm','estrutura'),('Músculos intercostais externos',138,'External intercostal muscles.*','estrutura'),('Músculos intercostais internos',138,'Internal intercostal muscles.*','estrutura')]:add(g,label,page,names,kind)
# Appended after the first stable release: explicit labels from professor's slides.
g='Laringe: músculos extrínsecos'
for label,names in [('Músculos digástricos','Anterior belly of digastric muscle.*|Posterior belly of digastric muscle.*|Intermediate tendon of digastric muscle.*'),('Músculos milo-hióideos','Mylohyoid muscle.*'),('Músculos gênio-hióideos','Geniohyoid muscle.*'),('Músculos estilo-hióideos','Stylohyoid muscle.*'),('Músculos tireo-hióideos','Thyrohyoid muscle.*'),('Músculos esternotireóideos','Sternothyroid muscle.*'),('Músculos esterno-hióideos','Sternohyoid muscle.*'),('Músculos omo-hióideos','Omohyoid muscle.*')]:add(g,label,66,names)
g='Laringe: vasos e nervos'
for label,page in [('Nervos laríngeos superiores',81),('Ramos internos dos nervos laríngeos superiores',81),('Ramos externos dos nervos laríngeos superiores',81),('Nervos laríngeos recorrentes',81),('Nervos laríngeos inferiores',81),('Artérias laríngeas superiores',79),('Artérias laríngeas inferiores',79)]:add(g,label,page)
add('Laringe: cartilagens e membranas','Osso hioide',56,'Hyoid bone')
for label,name in [('Ossos lacrimais','Lacrimal bone.*'),('Osso esfenoide','Sphenoid bone'),('Ossos palatinos','Palatine bone.*')]:add('Nariz e cavidade nasal',label,16,name)
add('Seios paranasais','Hiato semilunar',36,'Mucosa of nasal cavity','espaco')
add('Laringe: músculos e cavidade','Ádito da laringe',72,'Epiglottis|Arytenoid cartilage.*','abertura')
# Visual inspection of p.104 confirms two borders; the posterior border remains complementary.
for a in rows:
 if a['id'] in ['R158','R160']:
  a.update(fonte='resp_slides',pagina=104,escopo='principal',origem_escopo='Rótulo explícito na figura do pulmão esquerdo, slide 104; extensão bilateral é anatômica.')
 if a['id'] in ['R006','R009','R010','R011']:a['pagina']=10
 if a['id'] in ['R138','R139','R140','R148','R149']:a['pagina']=103
 a['fonte']='respiratorio' if a['fonte']=='resp_slides' else a['fonte']
# Supplemental source verbatim array preservation without executing JavaScript.
raw=(SRC/'03_Materiais_Locais/Roteiro_respiratorio/app.js.txt').read_text()
original=[]
for si,(sec,title,content) in enumerate(re.findall(r'\{secao:"([^"]+)", titulo:"([^"]+)", itens:\[(.*?)\]\}',raw,re.S)):
 original.append({'originalId':f'app_section_{si}','sectionIndex':si,'secao':sec,'titulo':title,'itens':[{'originalId':f'app_section_{si}_item_{ii}','texto':label} for ii,label in enumerate(re.findall(r'"([^"]+)"',content))]})
assert len(original)==8
sources=[{'id':'resp_slides','label':'Sistema Respiratório Medicina — Carmem Patrícia Barbosa','kind':'slides','type':'slides','pageCount':144,'reviewStatus':'Texto extraído; inspeção visual selecionada, não certificação integral das figuras.'},{'id':'roteiro_complementar','label':'Roteiro respiratório — Cláudia Regina Pinheiro Lopes','kind':'outline','type':'outline','reviewStatus':'Lista complementar local; não roteiro oficial de Carmem.'}]+[{'id':n,'label':f'Respiratório — Parte {n[1]}','kind':'lecture','type':'lecture','reviewStatus':'ASR automática; trechos localizados não equivalem a revisão integral do áudio.'} for n in ['R1','R2','R3','R4']]
method={'titulo':'Roteiro de estudo — derivado dos slides de Carmem','oficialidade':'Não foi localizado roteiro oficial respiratório da Carmem. Os IDs R### são identificadores editoriais estáveis, não numeração da professora.','regra':'Alvos explícitos em texto/figuras dos slides ou discussão correspondente; lista Cláudia preservada como complementar. Não é declaração do conteúdo da prova.','quantificacao':'Uma região da mesma malha pode atender um alvo de identificação após validação visual. Camada, espaço, microestrutura e estrutura independente são diferentes. Não promover correspondência nominal para validação.'}
for s in sources:
 if s['id']=='resp_slides':s['id']='respiratorio'
(OUT/'requirements.json').write_text(json.dumps({'version':1,'system':'respiratory','metodo':method,'sources':sources,'roteiro_complementar_original':original,'alvos':rows},ensure_ascii=False,indent=2)+'\n')
# Evidence starts source anchored. Focused lecture ranges and visual observations are appended later.
criteria={'estrutura':'Localizar a estrutura na orientação correta e conferir limites, continuidade e relações; nome da peça não valida a anatomia.', 'regiao':'Delimitar região na superfície verdadeira e oferecer vista de reconhecimento sem rótulo. Um pin aproximado não comprova relevo ou limite.', 'abertura':'Mostrar abertura real e sua continuidade anatômica; não marcar uma parede fechada como óstio.', 'espaco':'Mostrar espaço entre limites anatômicos corretos; não tratar um vazio anatômico como peça sólida.', 'camada':'Identificar camada e superfície de contato; uma malha única de pleura não individualiza automaticamente todos os folhetos e recessos.', 'articulacao':'Localizar superfícies articulares em conjunto e reconhecer o movimento permitido, sem confundir com ligamento.', 'conjunto':'Reconhecer cada componente relevante e sua relação espacial; um único elemento não completa o conjunto.', 'microestrutura':'Usar figura ou esquema de escala adequada; não apresentar geometria macroscópica genérica como estrutura microscópica real.'}
evidence={'version':1,'date':'2026-09-28','sources':sources,'targets':[{'id':a['id'],'scopeSource':{'source':a['fonte'],'page':a['pagina']},'criterion':criteria[a['tipo']],'pages':[{'source':'resp_slides','page':a['pagina']}] if a['pagina'] else [],'lecture':[],'visuals':[],'readingNotes':[]} for a in rows],'limits':['IDs gerados para estudo; não são um roteiro oficial de prova.','As malhas ainda exigem inspeção anatômica individual.','Transcrições automáticas não serão copiadas como gabarito.']}
for e in evidence['targets']:
 for p in e['pages']:p['source']='respiratorio'
(OUT/'practice-evidence.json').write_text(json.dumps(evidence,ensure_ascii=False,indent=2)+'\n')
print('Requirements',len(rows),'available',sum(a['status']=='geometria_disponivel' for a in rows),'partial',sum(a['status']=='parcial_ou_a_conferir' for a in rows),'unlocated',sum(a['status']=='nao_localizado' for a in rows))
for group in dict.fromkeys(a['grupo'] for a in rows):
 aa=[a for a in rows if a['grupo']==group];print(aa[0]['id'],aa[-1]['id'],group)
